// <auto-generated />
using System;
using GadgetHubAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GadgetHubAPI.Migrations
{
    [DbContext(typeof(GadgetHubDBContext))]
    [Migration("20250925061513_AddGadgetHubSeedData")]
    partial class AddGadgetHubSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GadgetHubAPI.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("GadgetHubAPI.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GadgetHubAPI.Model.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("GadgetHubAPI.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "iPhone",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(1681),
                            Description = "Latest iPhone with titanium design and A17 Pro chip",
                            Name = "iPhone 15 Pro Max",
                            Price = 450000m,
                            Stock = 15,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2060)
                        },
                        new
                        {
                            Id = 2,
                            Category = "iPhone",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2407),
                            Description = "Pro iPhone with titanium design and advanced camera system",
                            Name = "iPhone 15 Pro",
                            Price = 380000m,
                            Stock = 20,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2408)
                        },
                        new
                        {
                            Id = 3,
                            Category = "iPhone",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2412),
                            Description = "Latest iPhone with Dynamic Island and USB-C",
                            Name = "iPhone 15",
                            Price = 320000m,
                            Stock = 25,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2413)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Mac",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2417),
                            Description = "Powerful MacBook Pro with M3 Max chip for professionals",
                            Name = "MacBook Pro 16-inch M3 Max",
                            Price = 850000m,
                            Stock = 8,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2418)
                        },
                        new
                        {
                            Id = 5,
                            Category = "Mac",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2421),
                            Description = "Compact MacBook Pro with M3 chip and Liquid Retina XDR",
                            Name = "MacBook Pro 14-inch M3",
                            Price = 650000m,
                            Stock = 12,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2422)
                        },
                        new
                        {
                            Id = 6,
                            Category = "Mac",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2424),
                            Description = "Large MacBook Air with M2 chip and all-day battery",
                            Name = "MacBook Air 15-inch M2",
                            Price = 420000m,
                            Stock = 18,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2425)
                        },
                        new
                        {
                            Id = 7,
                            Category = "iPad",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2429),
                            Description = "Professional iPad with M2 chip and Liquid Retina XDR",
                            Name = "iPad Pro 12.9-inch M2",
                            Price = 280000m,
                            Stock = 10,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2430)
                        },
                        new
                        {
                            Id = 8,
                            Category = "iPad",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2432),
                            Description = "Compact iPad Pro with M2 chip and ProMotion",
                            Name = "iPad Pro 11-inch M2",
                            Price = 220000m,
                            Stock = 15,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2433)
                        },
                        new
                        {
                            Id = 9,
                            Category = "iPad",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2436),
                            Description = "Powerful iPad Air with M1 chip and Touch ID",
                            Name = "iPad Air 10.9-inch M1",
                            Price = 150000m,
                            Stock = 20,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2437)
                        },
                        new
                        {
                            Id = 10,
                            Category = "Apple Watch",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2440),
                            Description = "Latest Apple Watch with S9 chip and advanced health features",
                            Name = "Apple Watch Series 9",
                            Price = 85000m,
                            Stock = 30,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2441)
                        },
                        new
                        {
                            Id = 11,
                            Category = "Apple Watch",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2443),
                            Description = "Affordable Apple Watch with essential features",
                            Name = "Apple Watch SE 2nd Gen",
                            Price = 45000m,
                            Stock = 35,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2444)
                        },
                        new
                        {
                            Id = 12,
                            Category = "Apple Watch",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2447),
                            Description = "Rugged Apple Watch for extreme sports and adventures",
                            Name = "Apple Watch Ultra 2",
                            Price = 120000m,
                            Stock = 12,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2448)
                        },
                        new
                        {
                            Id = 13,
                            Category = "AirPods",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2451),
                            Description = "Premium AirPods with Active Noise Cancellation",
                            Name = "AirPods Pro 2nd Gen",
                            Price = 65000m,
                            Stock = 40,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2452)
                        },
                        new
                        {
                            Id = 14,
                            Category = "AirPods",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2454),
                            Description = "Latest AirPods with spatial audio and adaptive EQ",
                            Name = "AirPods 3rd Gen",
                            Price = 35000m,
                            Stock = 50,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2455)
                        },
                        new
                        {
                            Id = 15,
                            Category = "AirPods",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2458),
                            Description = "Over-ear headphones with Active Noise Cancellation",
                            Name = "AirPods Max",
                            Price = 95000m,
                            Stock = 15,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2459)
                        },
                        new
                        {
                            Id = 16,
                            Category = "Apple TV",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2462),
                            Description = "Latest Apple TV with A15 Bionic chip and Siri Remote",
                            Name = "Apple TV 4K 3rd Gen",
                            Price = 45000m,
                            Stock = 25,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2463)
                        },
                        new
                        {
                            Id = 17,
                            Category = "Apple TV",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2465),
                            Description = "Apple TV with A8 chip and Siri Remote",
                            Name = "Apple TV HD",
                            Price = 25000m,
                            Stock = 30,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2466)
                        },
                        new
                        {
                            Id = 18,
                            Category = "Apple TV",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2469),
                            Description = "Apple TV 4K with A12 Bionic chip",
                            Name = "Apple TV 4K 2nd Gen",
                            Price = 35000m,
                            Stock = 20,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2470)
                        },
                        new
                        {
                            Id = 19,
                            Category = "Accessories",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2473),
                            Description = "Premium keyboard with trackpad for iPad Pro",
                            Name = "Magic Keyboard for iPad Pro",
                            Price = 85000m,
                            Stock = 15,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2474)
                        },
                        new
                        {
                            Id = 20,
                            Category = "Accessories",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2477),
                            Description = "Precision stylus for iPad Pro and iPad Air",
                            Name = "Apple Pencil 2nd Gen",
                            Price = 25000m,
                            Stock = 25,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2477)
                        },
                        new
                        {
                            Id = 21,
                            Category = "Accessories",
                            CreatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2480),
                            Description = "Wireless charger with magnetic alignment",
                            Name = "MagSafe Charger",
                            Price = 15000m,
                            Stock = 40,
                            UpdatedDate = new DateTime(2025, 9, 25, 6, 15, 12, 675, DateTimeKind.Utc).AddTicks(2481)
                        });
                });

            modelBuilder.Entity("GadgetHubAPI.Model.QuotationComparison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableStock")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistributorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstimatedDeliveryDays")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("QuotationComparisons");
                });

            modelBuilder.Entity("GadgetHubAPI.Model.Order", b =>
                {
                    b.HasOne("GadgetHubAPI.Model.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GadgetHubAPI.Model.OrderItem", b =>
                {
                    b.HasOne("GadgetHubAPI.Model.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GadgetHubAPI.Model.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GadgetHubAPI.Model.QuotationComparison", b =>
                {
                    b.HasOne("GadgetHubAPI.Model.Order", "Order")
                        .WithMany("QuotationComparisons")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GadgetHubAPI.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GadgetHubAPI.Model.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GadgetHubAPI.Model.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("QuotationComparisons");
                });

            modelBuilder.Entity("GadgetHubAPI.Model.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
